# Generated by Django 3.1.4 on 2021-01-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0004_auto_20210104_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveaux',
            name='etoiles',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
