# Generated by Django 3.1.4 on 2021-01-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0005_niveaux_etoiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveaux',
            name='etoiles',
            field=models.CharField(default='str', max_length=50, unique=True),
        ),
    ]
