# Generated by Django 3.1.4 on 2021-01-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0006_auto_20210122_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveaux',
            name='etoiles',
            field=models.CharField(default='str', max_length=50),
        ),
    ]
