# Generated by Django 3.1.4 on 2021-01-02 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.CharField(max_length=200, unique=True)),
                ('detail', models.CharField(max_length=2000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Niveaux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(max_length=200, unique=True)),
                ('intitule', models.CharField(max_length=2000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(auto_now_add=True)),
                ('intitule', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('logo_client', models.CharField(max_length=200, unique=True)),
                ('detail', models.CharField(max_length=2000, unique=True)),
                ('competences', models.ManyToManyField(blank=True, related_name='experience', to='comp.Competences')),
            ],
        ),
        migrations.AddField(
            model_name='competences',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comp.niveaux'),
        ),
    ]
