# Generated by Django 3.1.4 on 2021-01-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveaux',
            name='note',
            field=models.IntegerField(null=True),
        ),
    ]
