# Generated by Django 3.1.4 on 2021-02-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0005_niveaux_etoiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveaux',
            name='text',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='date_debut',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='date_fin',
            field=models.DateTimeField(),
        ),
    ]
