# Generated by Django 3.1.4 on 2021-02-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0008_auto_20210201_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences',
            name='detail',
            field=models.TextField(default=' '),
        ),
    ]
