# Generated by Django 3.1.4 on 2021-02-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0009_auto_20210201_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiences',
            name='detail_en',
            field=models.TextField(default=' '),
        ),
    ]
