# Generated by Django 3.1.4 on 2021-02-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0012_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(default=' ')),
            ],
        ),
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contacts',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
