# Generated by Django 3.1.4 on 2021-02-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0013_auto_20210212_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(default=' ', max_length=100, unique=True),
        ),
    ]
