# Generated by Django 3.1.4 on 2021-02-12 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0014_auto_20210212_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='comp.contacts'),
        ),
    ]
