# Generated by Django 3.1.4 on 2021-02-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0015_messages_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
