# Generated by Django 3.1.4 on 2021-02-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0016_auto_20210213_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
