# Generated by Django 3.1.4 on 2021-02-13 23:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0017_auto_20210213_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='contacts',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
